language: python

env:
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="lua=5.4"

before_install:
  - pip install hererocks
  - hererocks here --$LUA -r latest
  - source here/bin/activate
  - luarocks install luacheck

install:
  - make -C src -j test-comp LUA=lua LUA_INC_DIR=$(PWD)/here/include LUA51=
  - make -C src LUACHECK=luacheck test-global

script:
  - cd src; lua lune/base/base.lua

after_script:
  - echo 
