# -*-makefile-*-
LUA_PATH=./?.lua;$(HOME)/work/LuneScript/src/?.lua
LNSC=../../src/lnsc
LNSTAGS=../../../lnstags/lnstags


INFILE=lns/main.lns

help_sub: help
	@echo make test
	@echo make test_log


test:
	$(LNSC) lns/main.lns -shebang "$(INFILE)" dummy.lns
	$(LNSC) lns/main.lns -shebang test/shebang.lns dummy2.lns

test_log:
	$(LNSC) lns/main.lns -shebang -log "$(INFILE)" dummy.lns

