# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hererocks
        hererocks here --lua=5.3 -r latest
        pwd
        source here/bin/activate
        luarocks install luacheck
        sudo apt-get install -y liblua5.3-dev lua5.3
    - name: Test
      run: |
        source here/bin/activate
        make -C src -j test-comp LUA=lua5.3 LUA51=
        make -C src go-build LUA=lua5.3 LUA51=
        make -C src LUACHECK=luacheck test-global
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: test-result
        path: src/work/test*.result
        retention-days: 5

  docker-cent8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build src/test/docker/compose/centos8/docker --tag cent8_lns
        docker image rm cent8_lns


  docker-cent7:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build src/test/docker/compose/centos7/docker --tag cent7_lns
        docker image rm cent7_lns

  docker-alpine:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build src/test/docker/compose/alpine/docker --tag alpine_lns
        docker image rm alpine_lns

  docker-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build src/test/docker/compose/ubuntu/docker --tag ubuntu_lns
        docker image rm ubuntu_lns
